name: Bug
description: Report a bug.
title: '[Bug] '
labels: bug
body:

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: |
        Provide as much information as possible, videos, crash reports, etc.
    validations:
      required: true
  - type: textarea
    id: reproducing
    attributes:
      label: Steps to reproduce
      description: How do you trigger this bug?
      render: bash
    validations:
      required: true
  - type: input
    id: mod-version
    attributes:
      label: Meteor Plus Version
    validations:
      required: true
  - type: input
    id: mc-version
    attributes:
      label: Minecraft Version
    validations:
      required: true
  - type: dropdown
    id: operating-systems
    attributes:
      label: Operating System
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Before submitting a bug report
      options:
        - label: |
            This bug wasn't already reported.
          required: true
        - label: |
            This is a valid bug.
          required: true